### ISSUE TITLE
The time is off by seven hours

### ISSUE THREAD

**Issue by c17ap** [c17ap/BuildSessions#26]

**Comment by davish** [comment]
@cforster you said you fixed this?

**Comment by cforster** [comment]
I *think* this is about the way i parse the time from the picker.  It works
on local meteor but not on the server, which I think means there is a
problem with the locale (GMT-5).  I have a possible fix, but I'd rather
redeploy at night.

CF

**Comment by c17ap** [comment]
It's really strange that the time is off by seven hours now, it makes me think this isn't a problem with the timezone

**Comment by cforster** [comment]
I think a productive path might be to update the start and endtime pickers
based on the date picked.  then we could just pass those datetimes.

**Comment by c17ap** [comment]
would we not be using moments then?  how would that effect the rest of our code?
